spring.application.name=EMAIL-SERVICE

server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sk95satish@gmail.com
spring.mail.password=coojzmwlmqybbeya
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Related Configuration

spring.servlet.multipart.max-file-size= 100MB
spring.servlet.multipart.max-request-size= 20MB


# -----------------------------------------
#           Swagger Registration
#-----------------------------------------

api.version = 1.0.0
application-title = Email-Service
application-description = This app contain how to send Email, Email with/without html content, Email with/without attachment in spring boot.
application-terms-of-service = http://swagger.io/terms/
application-license-name = Apache 2.0
application-license-url = http://springdoc.org
#application-external-doc-name = Sequence Diagram
#application-external-doc-url = provide url here

springdoc.default-produces-media-type="application/json"
springdoc.cache.disabled=true
springdoc.override-with-generic-response=true
springdoc.swagger-ui.show-common-extensions=true
